### ISSUE TITLE
能否推荐或者基于python3版本做个

### ISSUE THREAD

**Issue by yaleimeng** [andelf/PyAIML#8]
当前版本似乎是基于python2的。不知道是否有支持python3和中文规则的类似项目，希望推荐一下。
感谢作者分享此项目。

**Comment by yaleimeng** [comment]
在读完代码之后自己改写了一个[py3Aiml_Chinese](https://github.com/yaleimeng/py3Aiml_Chinese)，欢迎前往。现关闭该Issue。

**Comment by andelf** [comment]
我更新下README 链接过去
